#!/usr/bin/ansible-playbook
---
- name: copy ami to regions
  hosts: localhost
  gather_facts: no
  vars:
    g_play_current_region: us-east-1
    g_play_aws_share_accounts: "{{ cli_aws_share_accounts | default(None) }}"
    g_play_regions_to_copy:
    - 'ap-northeast-1'
    - 'ap-northeast-2'
    - 'ap-south-1'
    - 'ap-southeast-1'
    - 'ap-southeast-2'
    - 'ca-central-1'
    - 'eu-central-1'
    - 'eu-west-1'
    - 'eu-west-2'
    - 'eu-west-3'
    - 'sa-east-1'
    - 'us-east-1'
    - 'us-east-2'
    - 'us-west-1'
    - 'us-west-2'

  tasks:
  - name: Ensure needed variables are set
    fail:
      msg: "Value {{ item }} is not set!"
    when: "{{ item }} is undefined"
    with_items:
    - cli_ami_name

  - name: remove the current region from the list of regions to copy to
    set_fact:
      l_regions_to_copy: "{{ g_play_regions_to_copy | difference([g_play_current_region]) }}"

  - name: debug the l_regions_to_copy
    debug:
      var: l_regions_to_copy

  - name: find the newly built AMI
    ec2_ami_find:
      region: "{{ g_play_current_region }}"
      name: "{{ cli_ami_name }}"
      no_result_action: fail
    register: ami_search
    retries: 30
    delay: 20
    until: "'results' in ami_search and ami_search.results"

  - name: debug the ami find
    debug:
      var: ami_search

  - name: setup the variable to enable sharing the ami
    set_fact:
      l_dest_account_id:
        user_ids: "{{ g_play_aws_share_accounts.split(',') }}"
    when: g_play_aws_share_accounts

  - name: Add launch and copy permissions to AMI to new aws account
    ec2_ami:
      region: "{{ g_play_current_region }}"
      image_id: "{{ ami_search['results'][0]['ami_id'] }}"
      launch_permissions: "{{ l_dest_account_id }}"
    when: g_play_aws_share_accounts
    retries: 30
    delay: 20

  - ec2_ami_copy:
      name: "{{ ami_search['results'][0]['name'] }}"
      source_region: "{{ g_play_current_region }}"
      region: "{{ item }}"
      source_image_id: "{{ ami_search['results'][0]['ami_id'] }}"
      tags: "{{ ami_search['results'][0]['tags'] }}"
    with_items: "{{ l_regions_to_copy }}"
